/* Generated by tools/gen_oled_font.py -- do not edit by hand. */

#ifndef OLED_FONT_H
#define OLED_FONT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#define OLED_FONT_W          5U
#define OLED_FONT_HEIGHT      7U
#define OLED_FONT_ADVANCE    6U   /* glyph + 1 px gap */
#define OLED_FONT_GLYPHS     57U

extern const uint8_t OLED_Font5x7[OLED_FONT_GLYPHS][5];
uint8_t OLED_FontIndex(char c);

#ifdef __cplusplus
}
#endif

#endif /* OLED_FONT_H */