/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * The heap lives in the DMA-accessible AXI SRAM (RAM region) and grows from
 * the '_end' linker symbol up to '_Heap_Limit'.  The MSP stack is separate,
 * in DTCM.  malloc()ed buffers are therefore reachable by GPDMA1, which the
 * USBPD stack relies on for its RX/TX DMA buffers.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end; /* Symbol defined in the linker script */
  extern uint8_t _Heap_Limit; /* Symbol defined in the linker script (end of DMA-accessible RAM) */
  const uint8_t *max_heap = (uint8_t *)&_Heap_Limit;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  /* Protect heap from growing past the end of the DMA-accessible RAM region */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}
#if defined(__PICOLIBC__)
/* Picolibc's malloc() calls sbrk(), not _sbrk().  Provide a real strong
 * definition here (an `__strong_reference` alias silently produced nothing
 * unless <sys/cdefs.h> happened to be included) so that picolibc's own
 * picosbrk.o is never pulled out of libc.a.  picosbrk.o needs the linker
 * script to define __heap_start/__heap_end, which the STM32CubeIDE scripts
 * (STM32H7R3Z8JX_ROMxspi1.ld) do not; without this definition the link fails
 * with "undefined reference to __heap_start".  Routing through _sbrk() also
 * keeps the heap inside the DMA-accessible AXI SRAM window described above.
 */
void *sbrk(ptrdiff_t incr)
{
  return _sbrk(incr);
}
#endif
